name: Build and Release

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
  push:
    branches: "**"
    tags:
      - "v*.*.*"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        shell: sh
        run: npm i -g prettier

      - name: Lint
        shell: sh
        continue-on-error: true # allow lints to fail
        run: prettier --check "*.{html,js,css}"

  build:
    runs-on: ubuntu-20.04
    needs: lint
    # build for pushes to master or tagged versions
    if: "github.ref == 'refs/heads/master' || github.ref_type == 'tag'"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Image Tag
        shell: sh
        run: |
          REF_NAME=$(printf "%s" "${{ github.ref_name }}" | sed -e "s|/|-|g")
          IMAGE_TAG="book-my-appointment:${REF_NAME}"
          if [ "${{ github.ref_type }}" = "branch" ]; then
            COMMIT_HASH=$(printf "%s" "${{ github.sha }}" | cut -c-6)
            IMAGE_TAG="${IMAGE_TAG}.${COMMIT_HASH}"
          fi
          echo "image tag: ${IMAGE_TAG}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> "${GITHUB_ENV}"

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and Publish Image
        uses: docker/build-push-action@v5
        with:
          context: .
          # only push to registry for tagged versions
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ env.IMAGE_TAG }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Upload Image
        uses: ishworkh/container-image-artifact-upload@v1.1.1
        with:
          image: ${{ env.IMAGE_TAG }}
          retention_days: 15
